name = "yaoiverse-pack"
author = "nutstompr"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abb25e2eeba81bd0ce192bde5e79a1b3c1fe810d413a6a95bd843223fde127a4"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks"
